syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.amaytechnosystems";
option java_outer_classname = "TomShiftData";


import "meta/RequestMetaData.proto";
import "meta/ResponseMetaData.proto";
import "object/BaseObject.proto";
//import "enum/Enums.proto";


package com.proto.tom.object;


message ShiftDataV1 {
  baseobject.AEquipment equipment=1;
  baseobject.AOperator operator =2;
  baseobject.AStation station =3;
  baseobject.AShift shift =4;
}

message ShiftRequestV1 {
  ShiftDataV1 shiftData = 1;
  meta.reqmetadata.RequestMetaData requestMetaData = 2;

}

message ShiftResponseV1 {
  meta.respmetadata.ResponseMetaData responseMetaData = 1;
}

//Request for current day's last shift id
message LastShiftRequestV1 {
  meta.reqmetadata.RequestMetaData requestMetaData = 1;
  baseobject.AEquipment equipment=2;
  baseobject.AStation station =3;
}

//Response of current day's last shift
message LastShiftResponseV1 {
  meta.respmetadata.ResponseMetaData responseMetaData = 1;
  ShiftDataV1 shiftData=2;
}