syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.amaytechnosystems";
option java_outer_classname = "TomTransactionData";


import "meta/RequestMetaData.proto";
import "meta/ResponseMetaData.proto";
import "object/BaseObject.proto";


package com.proto.tom.object;


message TicketDataV1 {
  baseobject.AEquipment equipment=1;
  baseobject.AOperator operator =2;
  baseobject.AStation station =3;
  baseobject.ATicket ticket=4;
  baseobject.AVersion versions=5;
}

message TicketRequestV1 {
  TicketDataV1 ticketData = 1;
  meta.reqmetadata.RequestMetaData requestMetaData = 2;

}

message TicketResponseV1 {
  meta.respmetadata.ResponseMetaData responseMetaData = 1;
}

message TicketRefundResponseV1 {
  baseobject.ATicket ticket=1;
  meta.respmetadata.ResponseMetaData responseMetaData = 2;
}

message TicketAnalysisResponseV1 {
  baseobject.ATicketAnalysis ticketAnalysis = 1;
  meta.respmetadata.ResponseMetaData responseMetaData = 2;
}