syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.amaytechnosystems";
option java_outer_classname = "TomTicketCancelData";


import "meta/RequestMetaData.proto";
import "meta/ResponseMetaData.proto";
import "object/BaseObject.proto";



package com.proto.tom.object;


message TicketCancelDataV1 {
  baseobject.ACancelTicket cancelTicketData = 1;
}

message TicketCancelRequestV1 {
  TicketCancelDataV1 ticketData = 1;
  meta.reqmetadata.RequestMetaData requestMetaData = 2;

}

message TicketCancelResponseV1 {
  meta.respmetadata.ResponseMetaData responseMetaData = 1;
}