writer1 = console
writer1.format = {date: HH:mm:ss.SSS} [{level}] {class} [{thread}] : {message}

writer2 = rolling file
writer2.format = {date: HH:mm:ss.SSS}  [{level}] {class} [{thread}] : {message}
writer2.file = logs/tom_{date: yyyy-MM-dd}_{count}.log
writer2.policies =  size:10 MB
writer2.convert = gzip
writer2.backups  = 5
writer2.latest   = logs/latest.log
writer2.level = INFO