syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.amaytechnosystems";
option java_outer_classname = "TOMService";

package com.proto.ag.service;

import "tom/TomTransactionData.proto";
import "tom/TomShiftData.proto";
import "tom/TomTicketAdjustedData.proto";
import "tom/TomTicketCanceData.proto";
import "tom/TomTicketRefundData.proto";
import "tom/TomTicketReplaceData.proto";
import "tom/TomVersionData.proto";
import "tom/TomStockData.proto";


service TomTransactionService {
  // Unary RPC method
  rpc PushTicketIssueInfo(tom.object.TicketRequestV1) returns (tom.object.TicketResponseV1);

  rpc UpdateShiftInfo(tom.object.ShiftRequestV1) returns (tom.object.ShiftResponseV1);

  rpc PushTicketAdjustedData(tom.object.TicketAdjustedRequestV1) returns (tom.object.TicketAdjustedResponseV1);

  rpc CancelTicket(tom.object.TicketCancelRequestV1) returns (tom.object.TicketCancelResponseV1);

  rpc ReplaceTicket(tom.object.TicketReplaceRequestV1) returns (tom.object.TicketReplaceResponseV1);

  rpc GetVersion(tom.object.VersionRequestV1) returns (tom.object.VersionResponseV1);

  rpc GetTicketByNumber(tom.object.TicketRequestV1) returns (tom.object.TicketRefundResponseV1);

  rpc RefundByNumber(tom.object.TicketRefundRequestV1) returns (tom.object.TicketRefundResponseV2);

  rpc PushStocksData(tom.object.TomStockRequestV1) returns (tom.object.TomStockResponseV1);

  rpc GetTicketAnalysisDataByNumber(tom.object.TicketRequestV1) returns (tom.object.TicketAnalysisResponseV1);

}
