syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.amaytechnosystems";
option java_outer_classname = "VersionData";


import "meta/RequestMetaData.proto";
import "meta/ResponseMetaData.proto";
import "object/BaseObject.proto";


package com.proto.tom.object;

message Version {
  baseobject.ADevice device=1;
}

message VersionRequestV1 {
  Version version = 1;
  meta.reqmetadata.RequestMetaData requestMetaData = 2;

}

message VersionResponseV1 {
  string version = 2;
  meta.respmetadata.ResponseMetaData responseMetaData = 1;
}