syntax = "proto3";

package com.proto.scu.object;

option java_multiple_files = true;
option java_package = "org.amaytechnosystems";
option java_outer_classname = "SCURevenueProto";


import "meta/RequestMetaData.proto";
import "meta/ResponseMetaData.proto";
import "object/BaseObject.proto";
import "google/protobuf/struct.proto";


message RevenueData {
  baseobject.AEquipment equipment=1;
  baseobject.ARevenue revenue=2;
}

message SCURevenueReportRequestV1 {
  baseobject.AEquipment equipment=1;
  string fromDate=2;
  meta.reqmetadata.RequestMetaData requestMetaData = 3;
}

message SCURevenueReportResponseV1 {
  string lastTransactionTime = 3;
  RevenueData revenueData = 2;
  meta.respmetadata.ResponseMetaData responseMetaData = 1;
}


message RevenueReportListRequest {
  google.protobuf.ListValue reports = 1;
  meta.reqmetadata.RequestMetaData requestMetaData = 2;

}

message RevenueReportListResponse {
  google.protobuf.ListValue reports = 1;
  meta.respmetadata.ResponseMetaData responseMetaData = 2;
}