syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.amaytechnosystems";
option java_outer_classname = "TomTicketReplaceData";


import "meta/RequestMetaData.proto";
import "meta/ResponseMetaData.proto";
import "object/BaseObject.proto";



package com.proto.tom.object;


message TicketReplaceDataV1 {
  baseobject.AEquipment equipment=1;
  baseobject.AOperator operator =2;
  baseobject.AStation station =3;
  baseobject.AReplaceTicket ticket =4;
}

message TicketReplaceRequestV1 {
  TicketReplaceDataV1 ticketData = 1;
  meta.reqmetadata.RequestMetaData requestMetaData = 2;

}

message TicketReplaceResponseV1 {
  meta.respmetadata.ResponseMetaData responseMetaData = 1;
}