syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.amaytechnosystems";
option java_outer_classname = "TomTicketRefundData";


import "meta/RequestMetaData.proto";
import "meta/ResponseMetaData.proto";
import "object/BaseObject.proto";



package com.proto.tom.object;


message TicketRefundDataV1 {
  baseobject.AEquipment equipment=1;
  baseobject.AOperator operator =2;
  baseobject.AStation station =3;
  baseobject.ARefundTicket refundInfo =4;
  baseobject.ATransaction transactionInfo = 5;
}

message TicketRefundRequestV1 {
  TicketRefundDataV1 ticketRefundData = 1;
  meta.reqmetadata.RequestMetaData requestMetaData = 2;

}

message TicketRefundResponseV2 {
  TicketRefundDataV1 ticketRefundData = 1;
  meta.respmetadata.ResponseMetaData responseMetaData = 2;
}