//syntax = "proto3";
//
//option java_multiple_files = true;
//option java_package = "org.amaytechnosystems";
//option java_outer_classname = "TomTicketsService";
//
//package com.proto.service;
//
//import "TomTickets.proto";
//import "TicketIssueData.proto";
//
//service TomTicketService {
//
//  // Bidirectional streaming RPC method
//  rpc StreamTicketInfo(stream tom.TicketInfoRequest) returns (stream tom.TicketInfoReply);
//
//  // Unary RPC method
//  rpc GetTicketInfo(tom.TicketInfoRequest) returns (tom.TicketInfoReply);
//
//  // Server-streaming RPC method
//  rpc ListTicketInfo(tom.TicketInfoRequest) returns (stream tom.TicketInfoReply);
//
//  // Client-streaming RPC method
//  rpc UploadTicketInfo(stream tom.TicketInfoRequest) returns (tom.TicketInfoReply);
//
//}
//
//service TomTicketInfoService {
//
//    // Unary RPC method
//    rpc PushTicketInfo(tom.TicketRequest) returns (tom.TicketResponse);
//
//    //Client RPC
//    rpc ClientStreamPushTicketInfo(stream tom.TicketRequest) returns (tom.TicketResponse);
//
//    //Client RPC
//    rpc BiDirectionalTicketInfo(stream tom.TicketRequest) returns (stream tom.TicketResponse);
//
//    //Server Stream RCP
//    rpc ServerStreamPullTicketInfo( tom.TicketRequest) returns (stream tom.TicketResponse);
//
//
//
//
//}
//
////service TicketIssueInfoService {
////
////  // Unary RPC method
////  rpc PushTicketIssueInfo(tissue.TicketRequestV1) returns (tissue.TicketResponseV1);
////
//////  //Client RPC
//////  rpc ClientStreamPushTicketInfo(stream tissue.TicketRequest) returns (tissue.TicketResponse);
//////
//////  //Client RPC
//////  rpc BiDirectionalTicketInfo(stream tom.TicketRequest) returns (stream tom.TicketResponse);
//////
//////  //Server Stream RCP
//////  rpc ServerStreamPullTicketInfo( tom.TicketRequest) returns (stream tom.TicketResponse);
//////
//////  // Unary RPC method
//////  rpc PushTicketInfoV1(tissue.TicketRequest) returns (tom.TicketResponse);
////
////
////}
